# Generated by Django 3.2.3 on 2021-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especialidade', models.CharField(choices=[('Cirurgião', 'Cirurgião'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Cardiologista', 'Cardiologista'), ('Pediatra', 'Pediatra'), ('Radiologista', 'Radiologista'), ('Ortopedista', 'Ortopedista'), ('Enfermeiro', 'Enfermeiro'), ('Técnico de Enfermagem', 'Técnico de Enfermagem')], max_length=50)),
                ('cpf', models.CharField(max_length=50)),
            ],
        ),
    ]
