# Generated by Django 3.2.3 on 2021-05-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField(null=True)),
                ('estado_atendimento', models.BooleanField(default=False)),
                ('cpf', models.CharField(max_length=14)),
                ('atend_desc', models.CharField(max_length=500)),
                ('profResponsavel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professionals.profissional')),
            ],
        ),
    ]
